functions:
  getAllCompanies:
    handler: src/handlers/getAllCompaniesHandler.getAllCompanies
    events:
      - httpApi:
          path: /companies
          method: get
  getCompanyById:
    handler: src/handlers/getCompanyByIdHandler.getCompanyById
    events:
      - httpApi:
          path: /companies/{company_id}
          method: get
  insertCompany:
    handler: src/handlers/insertCompanyHandler.insertCompany
    events:
      - httpApi:
          path: /companies
          method: post
  updateCompanyById:
    handler: src/handlers/updateCompanyByIdHandler.updateCompanyById
    events:
      - httpApi:
          path: /companies/{company_id}
          method: put
  archiveCompanyById:
    handler: src/handlers/archiveCompanyByIdHandler.archiveCompanyById
    events:
      - httpApi:
          path: /companies/{company_id}/archive
          method: delete
  getTeamsByCompanyId:
    handler: src/handlers/getTeamsByCompanyIdHandler.getTeamsByCompanyId
    events:
      - httpApi:
          path: /team/company/{company_id}
          method: get
  getTeamById:
    handler: src/handlers/getTeamByIdHandler.getTeamById
    events:
      - httpApi:
          path: /team/{team_id}
          method: get
  insertTeam:
    handler: src/handlers/insertTeamHandler.insertTeam
    events:
      - httpApi:
          path: /team
          method: post
  updateTeamById:
    handler: src/handlers/updateTeamByIdHandler.updateTeamById
    events:
      - httpApi:
          path: /team/{team_id}
          method: put
  archiveTeam:
    handler: src/handlers/archiveTeamHandler.archiveTeam
    events:
      - httpApi:
          path: /team/{team_id}/archive
          method: delete
  getEmployeesByCompanyId:
    handler: src/handlers/getEmployeesByCompanyIdHandler.getEmployeesByCompanyId
    events:
      - httpApi:
          path: /employees/company/{company_id}
          method: get
  getEmployeesByTeamId:
    handler: src/handlers/getEmployeesByTeamIdHandler.getEmployeesByTeamId
    events:
      - httpApi:
          path: /employees/team/{team_id}
          method: get
    # getEmployeeById:
    #   handler: index.getEmployeeById
    #   events:
    #     - httpApi:
    #         path: /employees/{employee_id}
    #         method: get
    # insertEmployee:
    #   handler: index.insertEmployee
    #   events:
    #     - httpApi:
    #         path: /employees
    #         method: post
    # editEmployeeById:
    #   handler: index.editEmployeeById
    #   events:
    #     - httpApi:
    #         path: /employees/{employee_id}
    #         method: put
    # archiveEmployee:
    #   handler: index.archiveEmployee
    #   events:
    #     - httpApi:
    #         path: /employees/archive/{employee_id}
    #         method: delete